### ISSUE TITLE
MDS Legacy used to support : as well as = in the body for minting a DOI

### ISSUE THREAD

**Issue by richardhallett** [datacite/poodle#16]
The legacy MDS code used to support sending the body data for a POST operation with a colon ":" to seperate the keys, but now only equals "=" works, though with equals this is what our documentation says.

e.g. this works
```
doi= 10.5072/JQX3-61AT
url= http://example.org/
```
And this doesn't:
```
doi: 10.5072/JQX3-61AT
url: http://example.org/
```
The question is whether we want to add support for this, or just deal with on a case by case basis any of those using the other way.

Child of #11

**Comment by mfenner** [comment]
I would not support `:` as delimiter, as it seems that only a very small number of clients use this format, and it is easy to change the format that the client sends.

**Comment by richardhallett** [comment]
Okay great, in which case closing this issue as it can be solved easier through documentation and/or client updates.
