### ISSUE TITLE
MDS call GET /doi returns incomplete list for repository

### ISSUE THREAD

**Issue by richardhallett** [datacite/poodle#31]
Call to the /doi endpoint for MDS appears to be returning incorrect list of DOI's and excluding some associated prefixes to a particular repository.

e.g. http -a datacite.datacite:password https://mds.test.datacite.org/doi

See also comments on #30

**Comment by mfenner** [comment]
The underlying problem is limitations of the handle server REST API compared to using the Java client. The server returns a list of DOIs by prefix.

**Comment by richardhallett** [comment]
Based on internal conversations, as per the previous comment, this is limited due to the way we obtain the dois from the handle server by prefix. At this time it's preferred people use the rest API to get list of dois.
