### ISSUE TITLE
Error when requesting DOI media

### ISSUE THREAD

**Issue by hevp** [datacite/poodle#33]
When trying to get the media of a DataCite DOI through the MDS API:

`GET https://mds.test.datacite.org/media/10.21945/JZ1M-K167`

with basic authentication, I get the following error:

```
400 Bad Request: undefined method `page' for #<Media::ActiveRecord_AssociationRelation:0x00007fe91a6ab188>
```

The DOI itself resolves without problem, as does the metadata.

**Comment by mfenner** [comment]
This error us caused by the REST API, which processes the MDS API requests. This was caused by a missing dependency, and is now fixed.
