### ISSUE TITLE
API change for draft DOIs with no target?

### ISSUE THREAD

**Issue by MattBlissett** [datacite/poodle#7]
Hi,

First reported to us on 17 July, we've had problems reserving then updating DOIs. I think there has been a change to the MDS API.

After reserving a DOI, for example 10.5072/gbif.1565198687227370, [our client](https://github.com/gbif/gbif-doi/blob/gbif-doi-1.7/src/main/java/org/gbif/doi/service/datacite/DataCiteService.java#L83) would then request https://mds.datacite.org/doi/10.5072/gbif.1565198687227370 and either receive an HTTP 200 with an empty body, or for test DOIs possibly the URL "http://www.datacite.org/testprefix".

This call now returns 404.

Once a target URL has been set, this request works as expected: https://mds.datacite.org/doi/10.5072/gbif.1565512933685182

Additionally, and possibly related although less important to us, the HTTP call to delete a draft DOI appears to have changed.  Previously, it would be https://mds.datacite.org/metadata/10.5072/gbif.1565198687227370 but it new seems to be https://mds.datacite.org/doi/10.5072/gbif.1565198687227370

Before today, we last ran [our integration tests](https://builds.gbif.org/job/gbif-doi/) on 10 April, so I'm not sure when this change was introduced.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_cxbn)

**Comment by MattBlissett** [comment]
Thanks for the email Martin, I need to move the discussion here as we have users who want to track progress.

> With this in mind, can you clarify the following
>
>>  After reserving a DOI, for example 10.5072/gbif.1565198687227370
>
> What do you mean by that, an MDS API call to POST /metadata? You can't do PUT /doi/10.5072/gbif.1565198687227370 unless you have registered metadata first. And that hasn't change in years.

Yes, I mean something like

metadata.xml:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<resource xsi:schemaLocation="http://datacite.org/schema/kernel-3 http://schema.datacite.org/meta/kernel-3/metadata.xsd" xmlns="http://datacite.org/schema/kernel-3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <identifier identifierType="DOI">10.5072/GBIF.1533204862</identifier>
    <creators>
        <creator>
            <creatorName>Matt</creatorName>
            <nameIdentifier nameIdentifierScheme="ORCID" schemeURI="orcid.org">0000-0003-0623-6682</nameIdentifier>
        </creator>
    </creators>
    <titles>
        <title xml:lang="eng">reserve test</title>
    </titles>
    <publisher>GBIF</publisher>
    <publicationYear>2018</publicationYear>
    <resourceType resourceTypeGeneral="Dataset"/>
</resource>
```

```
curl -X POST -H "Content-Type:application/xml;charset=UTF-8" -i --user ***:*** -d @metadata.xml https://mds.datacite.org/metadata
```

This returns `201 Created`.  The DOI does not yet have a URL.

The change is the response to this query:

```
curl -i --user ***:*** https://mds.datacite.org/doi/10.5072/GBIF.1533204862
```

This used to return an HTTP 2xx status (I do not know if it was 200 or 204), and an empty HTTP body, but now returns 404.

I realise this might not be the expected use of the API — the current documentation doesn't say what ought to happen, and I don't have the old documentation — but it has worked this way for some years, and we have around 10 institutions running software we provide using this sequence.

**Comment by mfenner** [comment]
@MattBlissett now I understand the issue. This is indeed triggered by changes in our MDS code that was deployed to our test system on July 1 and our production system on July 16. Instead of status 204 the service returns status 404, which is of course confusing. 

I have written and deployed a fix, and you should soon see responses with status 204 again.
